routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();



Route::group(['middleware' => 'auth'], function () {
    
    Route::get('/', [
    	'as' => 'welcome',
    	'uses' => 'TaskController@show'
    	]);


    // маршрут к созданию заданий
	Route::get('create-tasks', [
		'as' => 'layouts.create-tasks',
		'uses' =>'TaskController@index'
	]);

	//маршрут к экшену сохраннения данных в бд
	 Route::post('/create-tasks', 'TaskController@store');
	
	// маршрут к настройкам пользователя
	/*Route::get('/employee-account', function () { 
    	return view('layouts.employee-account');
	});*/

	Route::resource('/employee-account', 'ProfileController');

	Route::get('task-view/{id}', [
			'as' => 'task-view.show',
			'uses' => 'TaskController@taskView'
	]);

	Route::put('task-view/{id}', [ 
		'as' => 'task-view.update',
		'uses' => 'TaskController@update' 
	]);

	Route::get('task-view/{id}/edit', [
		'as' => 'edit-task',
		'uses' => 'TaskController@edit'
		]);

	Route::put('task-view/{id}/edit', 'TaskController@updateTask');

	Route::delete('task-view/{id}', 'TaskController@deleteTask');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        
                        <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                            @if (Auth::guest())
                                <li><a href="{{ route('login') }}">Login</a></li>
                                <li><a href="{{ route('register') }}">Register</a></li>
                            @else
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                                Logout
                                            </a>

                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>
                                        </li>
                                    </ul>
                                                        
                                </li>
                            @endif
                        </ul>
                        <ul class="nav nav-pills">
                            <li class="active">
                                <a href="{{ url('/') }}">Мои задачи<span class="badge">{{ Auth::user()->task->count() }}</span></a>
                            </li>
                            <li><a href="{{ url('employee-account') }}">Настройки</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        @yield('content')

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/create-tasks.blade.php
@extends('layouts.app')
@section('content')

    @if(Session::has('success'))
    
        <div class="container">
            <div class="row">
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>

    @endif
			{{-- <div class="col-md-3">
				<img class="img-responsive img-rounded" src="http://st.depositphotos.com/2313517/3165/i/950/depositphotos_31654589-stock-photo-dropped-ice-cream-cone.jpg"><a class="btn btn-block btn-default">Удалить</a>
			</div>
			<div class="col-md-3">
				<img src="http://st.depositphotos.com/2313517/3165/i/950/depositphotos_31654589-stock-photo-dropped-ice-cream-cone.jpg" class="img-responsive img-rounded"><a class="btn btn-block btn-default">Удалить</a>
			</div> --}}
		

        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <form role="form" method="POST" action="{{ action('TaskController@store') }}" enctype="multipart/form-data" >
                        {{ csrf_field() }}

                            <input type="hidden" name="created_by" value={{$created_by}}>

				 			<div class="form-group">
                            	<label class="control-label">Название:</label>
                            	<input class="form-control" name="title" type="text">
                            </div>

                           <div class="form-group">
                                <label class="control-label">Фото</label>
                                <input name="image" type="file">
                            </div>

                            <div class="form-group">
                            	<label class="control-label">Описание:</label>
                            	<input class="form-control" name="description" type="text">
                            </div>
                            
                            <div class="form-group">
                                <div class="radio">
                                    <label class="radio-inline">
                                        <input type="radio" name="isUrgent" id="optionsRadios1" value="1" checked="">Срочно
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="isUrgent" id="optionsRadios2" value="0" checked="">&nbsp;Сегодня
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label">Отдел</label>
                                <select class="form-control">
                                    <option>1</option>
                                    <option>2</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label">Сотрудник</label>
                                <select class="form-control" name="assigned_to">
                                

                                @foreach($users as $user)
                                    {<option value = "{{ $user->id }}" >{{ $user->name }} {{ $user->surname }}</option>
                                @endforeach

                                </select>
                            </div>
                            
                            
                        	<div class="form-group">
                        		<label class="control-label">Дополнительная информация</label>
                        		<textarea class="form-control" name="additional" type="text"></textarea>
                        	</div>

                        	<button type="submit" class="btn btn-block btn-default btn-lg">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/layouts/edit-task.blade.php
@extends('layouts.app')
@section('content')
<div class="section">
	<div class="container">
		<div class="row">
            @if(Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
			{{-- <div class="col-md-3">
				<img class="img-responsive img-rounded" src="http://st.depositphotos.com/2313517/3165/i/950/depositphotos_31654589-stock-photo-dropped-ice-cream-cone.jpg"><a class="btn btn-block btn-default">Удалить</a>
			</div>
			<div class="col-md-3">
				<img src="http://st.depositphotos.com/2313517/3165/i/950/depositphotos_31654589-stock-photo-dropped-ice-cream-cone.jpg" class="img-responsive img-rounded"><a class="btn btn-block btn-default">Удалить</a>
			</div> --}}
		</div>
	</div>
</div>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <form role="form" method="POST" action="{{ action( 'TaskController@updateTask', ['id' => $task->id] ) }}" enctype="multipart/form-data" >
                        {{ csrf_field() }}

				 		{{ method_field('PUT') }}
                            {{-- <input type="hidden" name="created_by" value={{$created_by}} --}}
                           {{-- @foreach($created_by as $initials)
                            "{{$initials->surname}} {{$initials->name}} {{$initials->middlename}}"
                           @endforeach >--}}

				 			<div class="form-group">
                            	<label class="control-label">Название:</label>
                            	<input class="form-control" name="title" type="text" value="{{$task->title}}">
                            </div>

                           <div class="form-group">
                                <label class="control-label">Фото</label>
                                {{-- <input type="file" multiple="multiple" name="image, image2, image3" accept="image" required="required" title="Необходимо выбрать минимум один файл" > --}}
                                <input name="image" type="file">
                                {{-- <input name="image2" type="file">
                                <input name="image3" type="file"> --}}

                            </div>

                            <div class="form-group">
                            	<label class="control-label">Описание:</label>
                            	<input class="form-control" name="description" type="text" value="{{$task->description}}">
                            </div>
                            
                            <div class="form-group">
                                <div class="radio">
                                    <label class="radio-inline">
                                        <input type="radio" name="isUrgent" id="optionsRadios1" value="1" checked="">Срочно
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="isUrgent" id="optionsRadios2" value="0" checked="">&nbsp;Сегодня
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label">Отдел</label>
                                <select class="form-control">
                                    <option>1</option>
                                    <option>2</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label">Сотрудник</label>
                                <select class="form-control" name="assigned_to">
                                

                                @foreach($users as $user)
                                    {<option value = "{{ $user->id }}" >{{ $user->name }} {{ $user->surname }}</option>
                                    {{-- <option>{{ $user->id }}</option> --}}
                                @endforeach

                                </select>
                            </div>
                            
                            
                        	<div class="form-group">
                        		<label class="control-label">Дополнительная информация</label>
                        		<textarea class="form-control" name="additional" type="text" value="{{$task->additional}}" placeholder="{{$task->additional}}"></textarea>
                        	</div>

                        	<button type="submit" class="btn btn-block btn-default btn-lg">Обновить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/layouts/employee-account.blade.php
@extends('layouts.app')

@section('content')

<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<form role="form" method="POST" action="{{ route('employee-account.update', $user->id) }}" >
				 {{ csrf_field() }}
				 {{ method_field('PUT') }}
				 	@if(Session::has('success'))
	    				<div class="alert alert-success">
	        				{{ Session::get('success') }}
	    				</div>
					@endif

					<div class="form-group{{ $errors->has('surname') ? ' has-error' : '' }}">
						<label class="control-label" for="exampleInputEmail1">Фамилия</label>
							<input class="form-control" id="exampleInputEmail1" name="surname" type="text" value="{{ $user->name }}">
						@if ($errors->has('surnaname'))
                            <span class="help-block">
                                <strong>{{ $errors->first('surname') }}</strong>
                            </span>
                        @endif
					</div>

					<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
						<label class="control-label">Имя</label>
							<input class="form-control" type="text" name="name" value="{{ $user->name }}">
						@if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
					</div>

					<div class="form-group{{ $errors->has('middlename') ? ' has-error' : '' }}">
						<label class="control-label">Отчество</label>
							<input class="form-control" type="text" name="middlename" value="{{ $user->middlename }}">
						@if ($errors->has('middlename'))
                            <span class="help-block">
                                <strong>{{ $errors->first('middlename') }}</strong>
                            </span>
                        @endif
					</div>

					<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
						<label class="control-label">Телефон</label>
							<input class="form-control" type="text" name="phone" value="{{ $user->phone }}">
						@if ($errors->has('phone'))
                            <span class="help-block">
                                <strong>{{ $errors->first('phone') }}</strong>
                            </span>
                        @endif
					</div>

					<div class="form-group">
						<label class="control-label">Эл. почта</label>
							<input class="form-control" type="text" disabled="disabled"></div>

					<div class="form-group">
						<label class="control-label">Отдел</label>
							<input class="form-control" type="text" disabled="disabled"></div>

				<button type="submit" class="btn btn-block btn-default">Сохранить</button>
				
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/layouts/task-view.blade.php
@extends('layouts.app')
@section('content')

        <div class="container">
            <div class="row">
                @if(Session::has('success'))
                     <div class="alert alert-success">
                         {{ Session::get('success') }}
                    </div>
                @endif
            </div>
        </div>    

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>{{ $task->title }} <a href="{{ url('task-view/' . $task->id . 'edit') }}" class="btn btn-primary">Изменить</a>
                        <form role="form" method="POST" action="{{ action('TaskController@deleteTask', ['id' => $task->id]) }}" enctype="multipart/form-data" style="display: inline;" >
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </form></h1> 
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p>Создал: {{ date('d-m-Y H:i', strtotime($task->created_at)) }}
                        <br>
                        <br>

                        @foreach ($task_creator as $details)
                            <b>{{$details->surname}} {{$details->name}} {{$details->middlename}}&nbsp;</b>(отдел проверки качества)
                            <br>
                            <br>
                            <a href="{{$details->phone}}">Телефон: {{$details->phone}}</a>
                            <br>
                            <br>
                            <br>
                        @endforeach
                    </p>
                </div>

                <div class="col-md-6">
                    <p>Исполнитель:&nbsp;
                        <br>
                        <br>
                        @foreach ($task_performer as $details)
                            <b>{{$details->surname}} {{$details->middlename}} {{$details->name}}</b>&nbsp;(клининговый отдел)
                            <br>
                            <br>
                            <a href="{{$details->phone}}">{{$details->phone}}</a>
                            <br>
                            <br>
                            <br>
                        @endforeach 
                    </p> 
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <blockquote>{{ $task->description }}</blockquote>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                @foreach ( $task->images as $image )
                	<div class="col-md-3">
                        <img src="{{ asset($image->image) }}" class="img-responsive img-rounded">
                    </div>
                @endforeach
                
            </div>
        </div>

    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <form role="form" method="POST" action="{{ action('TaskController@update', ['id' => $task->id]) }}"  enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                        <div class="form-group">
                            <label class="control-label">Фото</label>
                            <input name="image" type="file">
                            <p class="help-block">Без фотографии выполнение задачи невозможно</p>
                        </div>

                        <div class="form-group">
                            <label class="control-label"></label>
                            <textarea class="form-control" name="comment" type="text" placeholder="Комментарий к заданию"></textarea>
                        </div>

                        <button type="submit" class="btn-lg btn-block btn-success" name="is_done" value="1">Сделано</button>
                        <div class="section">
                            <div class="container">
                                <div class="row">
                                    <button type="submit" class="btn btn-warning" name="is_tomorrow" value="1">Сделаю завтра</button>
                                </div>
                            </div>
                        </div>

                    </form>
       
                </div>
            </div>
        </div>
    </div>

    

    <script type="text/javascript" async="" src="main.js"></script>
    

@endsection